name: ejer2_rotar_pantalla
description: "Ejercicio 2 Mantener el estado de una lista al rotar la  pantalla"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
