name: repaso_examen
description: "Ejercicio planteado como repaso para el examen"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  shared_preferences: ^2.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
