name: ejer_sencillo_sqlite
description: "Ejercicio sencillo con sqlite."
publish_to: 'Estela de Vega'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true